version: "3.9"

services:
  bot:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app_net

networks:
  app_net:
    external: true  # Сеть сервиса
