
services:
  bot:
    build:
      context: .
    restart: always
    env_file:
      - .env
    image: my-telegram-bot-image
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - USER_ID=${USER_ID}
    ports:
      - "8000:8000"
    networks:
      - getcourse_app_net
networks:
  getcourse_app_net:
    external: true  # Сеть сервиса getcourse
